name: RegionUnstuckReloaded
version: '${version}'
main: org.bz69.regionUnstuckReloaded.RegionUnstuckReloaded
api-version: '1.20'
depend: [WorldGuard]
commands:
  regionunstuckreloaded:
    description: Teleport stuck WorldGuard region players outside the region
    usage: /regionunstuckreloaded <unstuck|reload>
permissions:
  regionunstuck.command:
    description: Allows using /regionunstuckreloaded unstuck
    default: true
  regionunstuck.reload:
    description: Allows reloading the configuration
    default: op
  regionunstuck.nocooldown:
    description: Allows bypassing cooldown set after teleport
    default: op
  regionunstuck.nodelay:
    description: Teleport instantly without delay
    default: op
  regionunstuck.*:
    description: Full access to all commands
    default: op
    children:
      regionunstuck.command: true
      regionunstuck.reload: true
      regionunstuck.nocooldown: true
      regionunstuck.nodelay: true
